### ISSUE TITLE
Autosave plugin ignores config changes (delay, messageType)?

### ISSUE THREAD

**Issue by damirt2017** [w8tcha/CKEditor-AutoSave-Plugin#104]
I read through all previously closed related bugs and it seems this issue was fixed at the latest in 0.17. I downloaded the last 0.18.1 plugin from the github and tried to change the delay to something other than 10 seconds but was not able to. I changed autosave_delay in CKEditor config (using it in DNN 9.1.1) and even changed the plugin.js to set the delay to 120 and messageType to no but the plugin still auto saves every 10 seconds and the notification message is still there. I would appreciate any suggestions on how to get the delay changed.

**Comment by w8tcha** [comment]
Yes this can not work, in the dnn provider the config settings for the autosave plugin where not updated for the latest version. This is fixed in the latest release  2.01.14.

If you change the value directly in the plugin.js you need to clear the browser cache otherwise the browser will not reload the updated js file
